# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rank',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Worst', 'Worst')], max_length=20),
        ),
    ]
